// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgX9gQaNzEA2dC5Q-0jj2ag4I1KRH7nKQ',
    appId: '1:932695552130:web:83ca1609da6823a2a6c49b',
    messagingSenderId: '932695552130',
    projectId: 'ai-app-for-glasses',
    authDomain: 'ai-app-for-glasses.firebaseapp.com',
    storageBucket: 'ai-app-for-glasses.appspot.com',
    measurementId: 'G-0XG9SE9CM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuBF30_seSWogmch3mxejHlYMxdFXRBk',
    appId: '1:932695552130:android:c9f7fd89d2e57200a6c49b',
    messagingSenderId: '932695552130',
    projectId: 'ai-app-for-glasses',
    storageBucket: 'ai-app-for-glasses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARRWHPauozjiXqzcbe7scp62hmF5E0bs',
    appId: '1:932695552130:ios:0d8cad84c01fce1fa6c49b',
    messagingSenderId: '932695552130',
    projectId: 'ai-app-for-glasses',
    storageBucket: 'ai-app-for-glasses.appspot.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCARRWHPauozjiXqzcbe7scp62hmF5E0bs',
    appId: '1:932695552130:ios:0d8cad84c01fce1fa6c49b',
    messagingSenderId: '932695552130',
    projectId: 'ai-app-for-glasses',
    storageBucket: 'ai-app-for-glasses.appspot.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgX9gQaNzEA2dC5Q-0jj2ag4I1KRH7nKQ',
    appId: '1:932695552130:web:5a2b73064f59bb83a6c49b',
    messagingSenderId: '932695552130',
    projectId: 'ai-app-for-glasses',
    authDomain: 'ai-app-for-glasses.firebaseapp.com',
    storageBucket: 'ai-app-for-glasses.appspot.com',
    measurementId: 'G-S3K6QN2G73',
  );
}
